/* C code generated by Lisaac compiler (www.lisaac.org) */

#define _LARGE_FILE_API
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE
int arg_count;
char **arg_vector;

/*==========================*/
/* EXTERNAL                 */
/*==========================*/

/* MEMORY */

#define MINIMUM_SIZE 256
void *table_size[MINIMUM_SIZE/sizeof(void *)];
void *last_block[64];

/* FLOAT_REAL */
#include <math.h>
/* SYSTEM */
#include <time.h>
/* SYSTEM_IO */

#include <stdio.h>
#include <stdlib.h>

/* Hardware 'print_char' */
void print_char(char car)
{
  fputc(car,stdout);
}

/* Hardware 'exit' */
int die_with_code(int code)
{
  exit(code);
}



/*==========================*/
/* TYPE                     */
/*==========================*/

/* Generic Object */
struct ___OBJ {
  unsigned int __id;
};

typedef struct li__R2B_struct __li__R2B;
typedef struct li__2E_struct __li__2E;
/* NULL */
#ifndef NULL
#define NULL ((void *)0)
#endif

typedef void * __li__GB;
typedef unsigned long __li__5E;
typedef unsigned int __li__U;
typedef signed int __li__K;
typedef unsigned char __li__BB;
/* li__R2B */
#define __li__R2B__ 0
struct li__R2B_struct {
  __li__K li__BYI;
  __li__K li__PYI;
  __li__BB *li__KYI;
};
/* li__2E */
#define __li__2E__ 1
struct li__2E_struct {
  __li__2E *li__4E;
  volatile __li__5E li__BF;
  __li__2E *li__CF;
  __li__2E *li__DF;
} __attribute__ ((packed));
typedef unsigned char __li__5B;
#define li__I__ 0
typedef char __li__C;

void *table_type[2];

/*==========================*/
/* GLOBAL                   */
/*==========================*/

__li__R2B li__R2B_;
#define li__R2B__ (&li__R2B_)

__li__2E li__2E_;
#define li__2E__ (&li__2E_)

__li__5E li__1MD;
__li__5E li__SMD;
__li__GB li__NM;
__li__2E *li__PAC;
__li__U li__ZC;
__li__5E li__04H;

/*==========================*/
/* FUNCTION HEADER          */
/*==========================*/

/* Source code */
static __li__GB li__II(__li__5E li__KI);
static __li__GB li__QJC(__li__5E li__SJC,__li__GB li__TJC,__li__U li__UJC);
static void li__QYI(__li__R2B *li__RYI,__li__BB li__SYI);
static void li__11(__li__U li__21);
static __li__2E* li__M5B(__li__5E li__O5B);
static __li__GB li__RUD(__li__U li__TUD);
static void li__YRK(__li__GB li__0RK,__li__GB li__1RK,__li__5E li__2RK);
static void li__CEF(__li__2E *li__DEF,__li__GB li__EEF,__li__5E li__FEF);
static void li__XJF(__li__2E *li__YJF);
static void li__TQF(__li__2E *li__UQF);
static __li__2E* li__IMD();

/*==========================*/
/* SOURCE CODE              */
/*==========================*/

int main(int argc,char **argv)
{
  __li__GB li__3AP,li__YS,li__VHP;
  __li__K li__S3,li__Z4H;
  __li__U li__KC,li__K5H;
  __li__R2B *li__F4H,*li__P5H,*li__0YI;
  __li__5E li__O4H,li__RHP,li__THP;
  volatile __li__U *li__YC;
  __li__BB li__QZI;
  __li__BB *li__VCP;
  arg_count  = argc;
  arg_vector = argv;
#ifdef _PTHREAD_H
  pthread_key_create(&current_thread, NULL);
  pthread_attr_init(&thread_attr);
  /*pthread_attr_setdetachstate(&thread_attr,PTHREAD_CREATE_DETACHED);*/
#endif
  ;
  li__1MD=((__li__5E ) 0);
  li__2E__->li__BF=((__li__5E ) 0);
  li__SMD=((__li__5E ) 0);
  li__NM=((__li__GB )(NULL));
  li__ZC= 0;
  li__04H=((__li__5E ) 0);
  li__3AP=li__II(((__li__5E ) 8));
  li__YC=((volatile __li__U *)li__3AP);
  li__ZC= 2;
  li__S3= 1;
  while ((li__S3 >=  0)) {
    li__YC[li__S3]= 0;
    li__S3=(__li__K)(li__S3 -  1);
  };
  li__II(((__li__5E ) 8));
  li__YC[ 1]= 9;
  li__YC[ 2]= 8;
  li__3AP=((__li__GB )li__YC);
  li__YS=((__li__GB )((__li__5E ) 8192));
  memcpy( (li__YS), (li__3AP), ((__li__U)(li__ZC <<  2)));
  li__KC=((volatile __li__U *)li__YS)[ 1];
  li__F4H=NULL;
  li__3AP=((__li__GB )(NULL));
  li__O4H=((__li__5E )sizeof(__li__R2B));
  if ((li__O4H ==  0)) {
    li__F4H=li__R2B__;
  } else /* FALSE */ {
    li__Z4H=__li__R2B__;
    li__04H=(__li__5E)(li__04H - (__li__5E)(((__li__5E ) 0) - li__O4H));
    if ((li__Z4H == (__li__K)(-  1))) {
      li__RHP=(__li__5E)(((__li__5E )((__li__K )(sizeof(void *)))) - ((__li__5E ) 1));
      li__THP=(__li__5E)((__li__5E)(li__O4H - (__li__5E)(((__li__5E ) 0) - li__RHP)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - li__RHP) - ((__li__5E ) 1)));
      li__VHP=li__QJC(li__THP,((__li__GB )(&(table_size[((__li__5E)(li__THP / ((__li__5E )((__li__K )(sizeof(void *))))))-1]))),((__li__U )li__THP));
      li__3AP=li__VHP;
    } else /* FALSE */ {
      li__K5H=((__li__U )li__Z4H);
      li__RHP=(__li__5E)(((__li__5E )((__li__K )(sizeof(void *)))) - ((__li__5E ) 1));
      li__VHP=li__QJC((__li__5E)((__li__5E)(li__O4H - (__li__5E)(((__li__5E ) 0) - li__RHP)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - li__RHP) - ((__li__5E ) 1))),((__li__GB )(&(table_type[(li__K5H)]))),(__li__U)(li__K5H |  1));
      li__3AP=li__VHP;
    };
    li__P5H=((__li__R2B *)li__3AP);
    li__F4H=li__P5H;
    *(li__P5H) = *(li__R2B__);
  };
  ((__li__R2B *)li__F4H)->li__PYI= 0;
  li__P5H=li__F4H;
  li__K5H= 0;
  li__S3= 0;
  li__Z4H= 0;
  if ((li__KC ==  0)) {
    li__QYI(((__li__R2B *)li__F4H),'0');
  } else /* FALSE */ {
    li__S3=(__li__K)(((__li__R2B *)li__F4H)->li__PYI +  1);
    li__K5H=li__KC;
    while ((li__K5H !=  0)) {
      li__QYI(((__li__R2B *)li__P5H),((__li__BB )(__li__5B)(((__li__5B )(__li__U)(li__K5H %  10)) + ((__li__5B )'0'))));
      li__K5H=(__li__U)(li__K5H /  10);
    };
    li__Z4H=((__li__R2B *)li__F4H)->li__PYI;
    while ((li__S3 < li__Z4H)) {
      li__0YI=((__li__R2B *)li__P5H);
      li__QZI=((__li__BB *)li__0YI->li__KYI)[(__li__K)(li__S3 -  1)];
      ((__li__BB *)li__0YI->li__KYI)[(__li__K)(li__S3 -  1)]=((__li__BB *)li__0YI->li__KYI)[(__li__K)(li__Z4H -  1)];
      ((__li__BB *)li__0YI->li__KYI)[(__li__K)(li__Z4H -  1)]=li__QZI;
      li__Z4H=(__li__K)(li__Z4H -  1);
      li__S3=(__li__K)(li__S3 +  1);
    };
  };
  li__P5H=((__li__R2B *)li__F4H);
  li__S3= 1;
  li__Z4H=li__P5H->li__PYI;
  li__VCP=li__P5H->li__KYI;
  while ((li__S3 <= li__Z4H)) {
    fputc((int)(((__li__BB *)li__VCP)[(__li__K)(li__S3 -  1)]),stdout);
    li__S3=(__li__K)(li__S3 +  1);
  };
  fputc((int)('\n'),stdout);
  li__11(li__YC[ 1]);
  return(0);
}


static __li__GB li__II(__li__5E li__KI)
/* (Expanded UINTEGER_CPU{li__5E}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__GB li__SI,li__K5B,li__LI;
  __li__5E li__UFP,li__3I,li__RW,li__Q4B;
  __li__2E *li__ZJ;
  li__SI=((__li__GB )(NULL));
  li__UFP=(__li__5E)(((__li__5E )((__li__K )(sizeof(void *)))) - ((__li__5E ) 1));
  li__3I=(__li__5E)((__li__5E)(li__KI - (__li__5E)(((__li__5E ) 0) - li__UFP)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - li__UFP) - ((__li__5E ) 1)));
  if ((li__3I <= ((__li__5E )(MINIMUM_SIZE)))) {
    li__RW=(__li__5E)(((__li__5E )((__li__K )(sizeof(void *)))) - ((__li__5E ) 1));
    li__Q4B=(__li__5E)((__li__5E)(li__3I - (__li__5E)(((__li__5E ) 0) - li__RW)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - li__RW) - ((__li__5E ) 1)));
    li__K5B=li__QJC(li__Q4B,((__li__GB )(&(table_size[((__li__5E)(li__Q4B / ((__li__5E )((__li__K )(sizeof(void *))))))-1]))),((__li__U )li__Q4B));
    li__SI=li__K5B;
  } else /* FALSE */ {
    li__ZJ=li__M5B(li__3I);
    li__SI=(void *)((unsigned long)((__li__GB )((__li__2E *)li__ZJ)) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))));
  };
  li__LI=li__SI;
  return(li__LI);
}

static __li__GB li__QJC(__li__5E li__SJC,__li__GB li__TJC,__li__U li__UJC)
/* (Expanded UINTEGER_CPU{li__5E},Expanded POINTER{li__GB},Expanded UINTEGER_32{li__U}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__GB li__YJC,li__0OO,li__WJC,li__3KC,li__4KC,li__RNC,li__VJC;
  li__YJC=((__li__GB )(NULL));
  li__0OO=((__li__GB *)li__TJC)[ 0];
  li__WJC=li__0OO;
  if ((li__0OO == (void *)NULL)) {
    li__3KC=li__RUD(li__UJC);
    li__WJC=li__3KC;
    li__4KC=(void *)((unsigned long)li__3KC - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )li__SJC)));
    li__YJC=li__4KC;
    ((__li__GB *)li__4KC)[ 0]=NULL;
    ((__li__GB *)li__TJC)[ 0]=li__4KC;
  } else /* FALSE */ {
    li__3KC=((__li__GB *)li__WJC)[ 0];
    li__YJC=li__3KC;
    if ((li__3KC == (void *)NULL)) {
      if (((void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)li__WJC - (unsigned long)li__NM) & (unsigned long)((__li__GB )((__li__5E ) 4095))) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )(__li__5E)(li__SJC <<  1)))) <= ((__li__GB )((__li__5E ) 4096)))) {
        li__YJC=(void *)((unsigned long)li__WJC - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )li__SJC)));
      } else /* FALSE */ {
        li__RNC=li__RUD(li__UJC);
        li__YJC=li__RNC;
      };
      ((__li__GB *)li__YJC)[ 0]=NULL;
      ((__li__GB *)li__TJC)[ 0]=li__YJC;
    } else /* FALSE */ {
      ((__li__GB *)li__WJC)[ 0]=(void *)((unsigned long)((__li__GB *)li__YJC)[ 0] & (unsigned long)((__li__GB )(__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1))));
      li__WJC=li__YJC;
    };
  };
  li__VJC=li__WJC;
  return(li__VJC);
}

static void li__QYI(__li__R2B *li__RYI,__li__BB li__SYI)
/* (Strict STRING{li__R2B},Expanded CHARACTER{li__BB}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__GB li__VSJ,li__JBK,li__FCK;
  __li__K li__23J,li__XZJ,li__B1J,li__2VL;
  __li__5E li__30J,li__50J,li__2DP,li__VBK,li__IEP,li__TUK,li__PVK;
  __li__5E li__IJL;
  __li__2E *li__RCK,*li__PUK,*li__3VK,*li__GJL,*li__GHP;
  __li__BB *li__ZSJ;
  if ((li__RYI->li__BYI <= li__RYI->li__PYI)) {
    if ((li__RYI->li__BYI ==  0)) {
      li__RYI->li__BYI= 32;
      li__VSJ=li__II(((__li__5E ) 32));
      li__ZSJ=((__li__BB *)li__VSJ);
      li__23J= 31;
      while ((li__23J >=  0)) {
        li__ZSJ[li__23J]='\0';
        li__23J=(__li__K)(li__23J -  1);
      };
      li__RYI->li__KYI=li__ZSJ;
    } else /* FALSE */ {
      li__23J=(__li__K)(li__RYI->li__BYI <<  1);
      li__ZSJ=((__li__BB *)li__RYI->li__KYI);
      li__XZJ=li__RYI->li__BYI;
      li__VSJ=((__li__GB )li__ZSJ);
      li__30J=((__li__5E )li__XZJ);
      li__50J=((__li__5E )li__23J);
      li__JBK=((__li__GB )(NULL));
      li__2DP=(__li__5E)(((__li__5E )((__li__K )(sizeof(void *)))) - ((__li__5E ) 1));
      li__VBK=(__li__5E)((__li__5E)(li__30J - (__li__5E)(((__li__5E ) 0) - li__2DP)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - li__2DP) - ((__li__5E ) 1)));
      li__30J=(__li__5E)(((__li__5E )((__li__K )(sizeof(void *)))) - ((__li__5E ) 1));
      li__2DP=(__li__5E)((__li__5E)(li__50J - (__li__5E)(((__li__5E ) 0) - li__30J)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - li__30J) - ((__li__5E ) 1)));
      if ((li__VBK <= ((__li__5E )(MINIMUM_SIZE)))) {
        li__FCK=li__II(li__2DP);
        li__JBK=li__FCK;
        li__YRK(li__VSJ,li__FCK,li__VBK);
        li__IEP=(__li__5E)(((__li__5E )((__li__K )(sizeof(void *)))) - ((__li__5E ) 1));
        li__FCK=((__li__GB *)((__li__GB )(&(table_size[((__li__5E)((__li__5E)((__li__5E)(li__VBK - (__li__5E)(((__li__5E ) 0) - li__IEP)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - li__IEP) - ((__li__5E ) 1))) / ((__li__5E )((__li__K )(sizeof(void *))))))-1]))))[ 0];
        ((__li__GB *)li__VSJ)[ 0]=(void *)((unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)(void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB *)li__FCK)[ 0]) - (unsigned long)((__li__GB )((__li__5E ) 1))) & (unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E ) 3))) - (unsigned long)((__li__GB )((__li__5E ) 1))))) - (unsigned long)((__li__GB )((__li__5E ) 1)));
        ((__li__GB *)li__FCK)[ 0]=li__VSJ;
      } else /* FALSE */ {
        li__RCK=((__li__2E *)(void *)((unsigned long)li__VSJ - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))));
        li__IEP=(__li__5E)(((__li__5E )(void *)((unsigned long)li__VSJ - (unsigned long)li__NM)) >>  26);
        li__PUK=NULL;
        li__TUK=((__li__5E ) 0);
        li__PVK=(__li__5E)(li__RCK->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1)));
        if ((li__2DP > li__PVK)) {
          if ((! ((__li__5E)(li__RCK->li__BF & ((__li__5E ) 2)) !=  0))) {
            li__3VK=((__li__2E *)(void *)((unsigned long)(void *)((unsigned long)((__li__GB )li__RCK) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )(__li__5E)(li__RCK->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1)))))));
            li__TUK=(__li__5E)((__li__5E)(li__2DP - li__PVK) - ((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))));
            if ((((__li__5E)(li__3VK->li__BF & ((__li__5E ) 1)) == ((__li__5E ) 0)) && ((__li__5E)(li__3VK->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1))) >= li__TUK))) {
              li__CEF(li__3VK,((__li__GB )li__TUK),li__IEP);
              li__RCK->li__BF=(__li__5E)((__li__5E)(li__RCK->li__BF - (__li__5E)(((__li__5E ) 0) - (__li__5E)(li__3VK->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 1)) - ((__li__5E ) 1))))) - (__li__5E)(((__li__5E ) 0) - ((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))));
              if (((__li__5E)(li__RCK->li__BF & ((__li__5E ) 2)) !=  0)) {
                last_block[(li__IEP)] = (li__RCK);
              } else /* FALSE */ {
                ((__li__2E *)(void *)((unsigned long)(void *)((unsigned long)((__li__GB )li__RCK) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )(__li__5E)(li__RCK->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1)))))))->li__4E=li__RCK;
              };
              li__PUK=li__RCK;
            };
          };
          if (((void *)li__PUK == (void *)NULL)) {
            li__3VK=li__M5B(li__2DP);
            li__PUK=li__3VK;
            li__YRK((void *)((unsigned long)((__li__GB )li__RCK) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))),(void *)((unsigned long)((__li__GB )((__li__2E *)li__3VK)) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))),li__PVK);
            li__3VK=((__li__2E *)(void *)((unsigned long)(void *)((unsigned long)((__li__GB )li__RCK) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )(__li__5E)(li__RCK->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1)))))));
            li__GJL=li__RCK->li__4E;
            li__IJL=(__li__5E)(li__RCK->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 1)) - ((__li__5E ) 1)));
            if ((((void *)li__GJL == (void *)NULL) || ((__li__5E)(((__li__2E *)li__GJL)->li__BF & ((__li__5E ) 1)) != ((__li__5E ) 0)))) {
              li__GJL=li__RCK;
              li__XJF(li__RCK);
            } else /* FALSE */ {
              li__IJL=(__li__5E)((__li__5E)(li__IJL - (__li__5E)(((__li__5E ) 0) - li__GJL->li__BF)) - (__li__5E)(((__li__5E ) 0) - ((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))));
            };
            if (((! ((__li__5E)(li__RCK->li__BF & ((__li__5E ) 2)) !=  0)) && ((__li__5E)(li__3VK->li__BF & ((__li__5E ) 1)) == ((__li__5E ) 0)))) {
              li__IJL=(__li__5E)((__li__5E)(li__IJL - (__li__5E)(((__li__5E ) 0) - li__3VK->li__BF)) - (__li__5E)(((__li__5E ) 0) - ((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))));
              li__TQF(li__3VK);
            };
            ((__li__2E *)li__GJL)->li__BF=li__IJL;
            if (((__li__5E)(((__li__2E *)li__GJL)->li__BF & ((__li__5E ) 2)) !=  0)) {
              last_block[(li__IEP)] = (li__GJL);
            } else /* FALSE */ {
              li__GHP=((__li__2E *)li__GJL);
              ((__li__2E *)(void *)((unsigned long)(void *)((unsigned long)((__li__GB )li__GHP) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )(__li__5E)(li__GHP->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1)))))))->li__4E=li__GJL;
            };
          };
        } else /* FALSE */ {
          li__PUK=li__RCK;
        };
        li__JBK=(void *)((unsigned long)((__li__GB )((__li__2E *)li__PUK)) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))));
      };
      li__ZSJ=((__li__BB *)li__JBK);
      li__B1J=(__li__K)(li__23J -  1);
      li__2VL=li__XZJ;
      while ((li__2VL <= li__B1J)) {
        li__ZSJ[li__2VL]='\0';
        li__2VL=(__li__K)(li__2VL +  1);
      };
      li__RYI->li__KYI=li__ZSJ;
      li__RYI->li__BYI=li__23J;
    };
  };
  ((__li__BB *)li__RYI->li__KYI)[li__RYI->li__PYI]=li__SYI;
  li__RYI->li__PYI=(__li__K)(li__RYI->li__PYI +  1);
}

static void li__11(__li__U li__21)
/* (Expanded UINTEGER_32{li__U}) Void Recursive, No inlinable. NO CONTEXT! */
{
  __li__U li__N2;
  __li__BB li__M2;
  li__M2=((__li__BB )(__li__5B)(((__li__5B )(__li__U)(li__21 %  10)) + ((__li__5B )'0')));
  li__N2=(__li__U)(li__21 /  10);
  if ((li__N2 !=  0)) {
    li__11(li__N2);
  };
  fputc((int)(li__M2),stdout);
}

static __li__2E* li__M5B(__li__5E li__O5B)
/* (Expanded UINTEGER_CPU{li__5E}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__2E *li__Q5B,*li__MBC,*li__P5B;
  li__Q5B=li__PAC;
  while ((((void *)li__Q5B != (void *)NULL) && ((__li__5E)(((__li__2E *)li__Q5B)->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1))) < li__O5B))) {
    li__Q5B=li__Q5B->li__CF;
  };
  if (((void *)li__Q5B == (void *)NULL)) {
    li__MBC=li__IMD();
    li__Q5B=li__MBC;
  };
  li__CEF(((__li__2E *)li__Q5B),((__li__GB )li__O5B),(__li__5E)(((__li__5E )(void *)((unsigned long)((__li__GB )((__li__2E *)li__Q5B)) - (unsigned long)li__NM)) >>  26));
  li__P5B=li__Q5B;
  return(li__P5B);
}

static __li__GB li__RUD(__li__U li__TUD)
/* (Expanded UINTEGER_32{li__U}) With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__5E li__VUD;
  __li__2E *li__YUD,*li__ZUD,*li__HVD;
  __li__GB li__TWD,li__UUD;
  __li__C li__YVD;
  li__VUD=((__li__5E ) 0);
  li__YUD=NULL;
  li__ZUD=NULL;
  li__IBE:
  {
    if ((li__VUD < li__1MD)) {
      li__HVD=((__li__2E *)(last_block[(li__VUD)]));
      li__YUD=li__HVD;
      li__YVD=(((__li__5E)(li__HVD->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1))) < ((__li__5E ) 4096)) || ((__li__5E)(li__HVD->li__BF & ((__li__5E ) 1)) == ((__li__5E ) 1)));
    } else /* FALSE */ {
      li__YVD=li__I__;
    };
    if (li__YVD) {
      li__VUD=(__li__5E)(li__VUD - (__li__5E)(((__li__5E ) 0) - ((__li__5E ) 1)));
      goto li__IBE;
    };
  };
  if ((li__VUD >= li__1MD)) {
    li__HVD=li__IMD();
    li__YUD=li__HVD;
  };
  ((__li__2E *)li__YUD)->li__BF=(__li__5E)(li__YUD->li__BF - ((__li__5E ) 4096));
  li__HVD=((__li__2E *)li__YUD);
  li__TWD=((__li__GB )((__li__2E *)(void *)((unsigned long)(void *)((unsigned long)((__li__GB )li__HVD) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )(__li__5E)(li__HVD->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1))))))));
  if (((__li__5E)(((__li__2E *)li__YUD)->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1))) < ((__li__5E )(MINIMUM_SIZE)))) {
    li__TQF(((__li__2E *)li__YUD));
    li__ZUD=li__YUD->li__4E;
    if (((void *)li__ZUD != (void *)NULL)) {
      ((__li__2E *)li__ZUD)->li__BF=(__li__5E)((__li__5E)(li__ZUD->li__BF - (__li__5E)(((__li__5E ) 0) - li__YUD->li__BF)) - (__li__5E)(((__li__5E ) 0) - ((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))));
      last_block[(li__VUD)] = (li__ZUD);
    };
  };
  ((__li__U *)li__TWD)[ 0]=li__TUD;
  li__UUD=(void *)((unsigned long)li__TWD - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E ) 4))));
  return(li__UUD);
}

static void li__YRK(__li__GB li__0RK,__li__GB li__1RK,__li__5E li__2RK)
/* (Expanded POINTER{li__GB},Expanded POINTER{li__GB},Expanded UINTEGER_CPU{li__5E}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__K li__PSK,li__1ZK;
  __li__GB *li__3RK,*li__4RK;
  li__PSK=(__li__K)(((__li__K )li__2RK) / ((__li__K )(sizeof(void *))));
  li__3RK=((__li__GB *)li__0RK);
  li__4RK=((__li__GB *)li__1RK);
  li__1ZK=(__li__K)(li__PSK -  1);
  while ((li__1ZK >=  0)) {
    li__4RK[li__1ZK]=li__3RK[li__1ZK];
    li__1ZK=(__li__K)(li__1ZK -  1);
  };
}

static void li__CEF(__li__2E *li__DEF,__li__GB li__EEF,__li__5E li__FEF)
/* (Strict MEMORY{li__2E},Expanded POINTER{li__GB},Expanded UINTEGER_CPU{li__5E}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__5E li__GEF,li__FFF;
  __li__2E *li__3FF;
  li__TQF(li__DEF);
  li__GEF=li__DEF->li__BF;
  li__FFF=(__li__5E)(li__GEF - ((__li__5E )li__EEF));
  if ((li__FFF > (__li__5E)((__li__5E)(((__li__5E )(MINIMUM_SIZE)) - (__li__5E)(((__li__5E ) 0) - ((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))) - (__li__5E)(((__li__5E ) 0) - ((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))))) {
    li__GEF=((__li__5E )li__EEF);
    li__3FF=((__li__2E *)(void *)((unsigned long)(void *)((unsigned long)((__li__GB )li__DEF) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)li__EEF)));
    li__3FF->li__4E=li__DEF;
    li__3FF->li__BF=(__li__5E)(li__FFF - ((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))));
    li__XJF(li__3FF);
    if (((__li__5E)(li__3FF->li__BF & ((__li__5E ) 2)) !=  0)) {
      last_block[(li__FEF)] = (li__3FF);
    } else /* FALSE */ {
      ((__li__2E *)(void *)((unsigned long)(void *)((unsigned long)((__li__GB )li__3FF) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )((__li__5E )(__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long)))))))) - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )(__li__5E)(li__3FF->li__BF & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 3)) - ((__li__5E ) 1)))))))->li__4E=li__3FF;
    };
  };
  li__DEF->li__BF=(__li__5E)((__li__5E)(((__li__5E ) 0) - (__li__5E)((__li__5E)((__li__5E)(((__li__5E ) 0) - li__GEF) - ((__li__5E ) 1)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 1)) - ((__li__5E ) 1)))) - ((__li__5E ) 1));
}

static void li__XJF(__li__2E *li__YJF)
/* (Strict MEMORY{li__2E}) Void No recursive, No inlinable. NO CONTEXT! */
{
  li__YJF->li__CF=li__PAC;
  li__YJF->li__DF=NULL;
  if (((void *)li__PAC != (void *)NULL)) {
    ((__li__2E *)li__PAC)->li__DF=li__YJF;
  };
  li__PAC=li__YJF;
}

static void li__TQF(__li__2E *li__UQF)
/* (Strict MEMORY{li__2E}) Void No recursive, No inlinable. NO CONTEXT! */
{
  __li__2E *li__VQF,*li__WQF;
  li__VQF=li__UQF->li__DF;
  li__WQF=li__UQF->li__CF;
  if (((void *)li__VQF == (void *)NULL)) {
    li__PAC=li__WQF;
  } else /* FALSE */ {
    ((__li__2E *)li__VQF)->li__CF=li__WQF;
  };
  if (((void *)li__WQF != (void *)NULL)) {
    ((__li__2E *)li__WQF)->li__DF=li__VQF;
  };
}

static __li__2E* li__IMD()
/* () With result No recursive, No inlinable. NO CONTEXT! */
{
  __li__GB li__UTE,li__WTE;
  __li__5E li__RTE,li__5TE;
  __li__K li__YAG;
  __li__2E *li__WND,*li__KMD;
  if ((li__SMD ==  0)) {
    li__UTE=((__li__GB )(NULL));
    li__WTE=((__li__GB )(NULL));
    li__RTE=((__li__5E ) 33554432);
    do {
      li__5TE=(__li__5E)(li__RTE * ((__li__5E ) 2));
      li__RTE=li__5TE;
      li__UTE=li__WTE;
      li__WTE=((__li__GB )(realloc((li__WTE),(li__5TE))));
    } while ((! ((li__WTE == (void *)NULL) || ((__li__5E)(li__5TE >>  20) ==  2048))));
    if ((li__WTE == (void *)NULL)) {
      li__RTE=(__li__5E)(li__RTE / ((__li__5E ) 2));
    } else /* FALSE */ {
      li__UTE=li__WTE;
    };
    li__SMD=li__RTE;
    li__NM=li__UTE;
  };
  li__RTE=(__li__5E)(li__1MD <<  26);
  li__1MD=(__li__5E)(li__1MD - (__li__5E)(((__li__5E ) 0) - ((__li__5E ) 1)));
  if (((__li__5E)(li__RTE - (__li__5E)(((__li__5E ) 0) - ((__li__5E ) 67108864))) > li__SMD)) {
    li__YAG= 1;
    while ((li__YAG <=  19)) {
      fputc((int)("Not enough memory.\n"[(__li__K)(li__YAG -  1)]),stdout);
      li__YAG=(__li__K)(li__YAG +  1);
    };
    exit(( 1));
  };
  li__WND=((__li__2E *)(void *)((unsigned long)li__NM - (unsigned long)(void *)((unsigned long)((__li__GB )((__li__5E ) 0)) - (unsigned long)((__li__GB )li__RTE))));
  li__WND->li__4E=NULL;
  li__WND->li__BF=(__li__5E)((__li__5E)(((__li__5E ) 0) - (__li__5E)((__li__5E)((__li__5E)(((__li__5E ) 0) - (__li__5E)((__li__5E)(((__li__5E ) 0) - (__li__5E)((__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 0)) - ((__li__5E ) 1)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E ) 2)) - ((__li__5E ) 1)))) - ((__li__5E ) 1))) - ((__li__5E ) 1)) & (__li__5E)((__li__5E)(((__li__5E ) 0) - ((__li__5E )(__li__K)( 67108864 - (__li__K)(((__li__K )(sizeof(void *))) + ((__li__K )(sizeof(unsigned long))))))) - ((__li__5E ) 1)))) - ((__li__5E ) 1));
  li__XJF(li__WND);
  last_block[((__li__5E)(li__1MD - ((__li__5E ) 1)))] = (li__WND);
  li__KMD=li__WND;
  return(li__KMD);
}
